name: Release Docker image
on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: ecadlabs/tezos_exporter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v2
      - run: go build -v .

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: |
          VERSION=$(echo "${{ github.ref }}" |  sed -E -e 's/.*\/v?(.*)/\1/')
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
